# Site settings
title: AFiniteNumberOfMonkeys
email: chaos@afnom.net
description: > # this means to ignore newlines until "baseurl:"
  AFiniteNumberOfMonkeys -- the Hacking Club of University of Birmingham.
  Any problem can be solved by enough monkeys acting completely at random
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://afnom.net" # the base hostname & protocol for your site
github_username:  afnom

# Build settings
markdown: kramdown
highlighter: rouge
collections_dir: collections

collections:
  writeups:
    permalink: /:collection/:year/:title/
    output: true
  wtctf:
    permalink: /:collection/:year/:title/
    output: true
defaults:
  -scope:
      path: ""
  values:
    layout: post
